#!/usr/bin/env bash
is_gz_exist=1
has_found=0
while read line
do
	has_found=0
	IFS=:
	for man_path in `manpath`
	do
		if [ -f "$man_path/man3/$line.3.gz" ]
		then
			cp $man_path/man3/$line.3.gz ~/
			gunzip -k ~/$line.3.gz
			is_gz_exist=2
			has_found=1

		elif [ -f "$manpath/man3/$line.3" ]
		then
			cp $man_path/man3/$line.3 ~/
			is_gz_exist=3
			has_found=1
		fi
	done

	if [ $has_found == 1 ]
	then
		if [ $is_gz_exist == 2 ] || [ $is_gz_exist == 3 ]
		then
			echo $(sed -n '/#include/ p ' ~/$line.3 | sed -E 's/.B #include <//' | sed -E 's/>//' |  sed -E 's/ .*//g' | sed -E 's/#include//g')
			rm ~/$line.3
		fi
		if [ $is_gz_exist == 2 ]
		then
			rm ~/$line.3.gz
		fi
		is_gz_exist=1
	else
		echo "---"
	fi
done
